[package]
name = "space_bevy_xpbd_plugin"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Space XPBD plugin for space_editor crate"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy.workspace = true 
space_editor_ui.workspace = true
space_shared.workspace = true
bevy_xpbd_3d = { workspace = true, features = ["3d", "f32", "collider-from-mesh", "debug-plugin", "default-collider", "parry-f32"] }
bevy-inspector-egui.workspace = true 
workspace-hakari = { version = "0.1", path = "../../workspace-hakari" }

[lints]
workspace = true
